# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigLint < Formula
  desc ""
  homepage ""
  version "1.0.8-beta"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stelligent/config-lint/releases/download/v1.0.8-beta/config-lint_1.0.8-beta_Darwin_x86_64.tar.gz"
    sha256 "0c661fb9295d6f56d976f320bc48236d0c4fe0c7fae029ed82b4ab3362df5d87"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/stelligent/config-lint/releases/download/v1.0.8-beta/config-lint_1.0.8-beta_Linux_x86_64.tar.gz"
      sha256 "c84d50b06238a1f63d76d55598e633932092a719e2ce83464a2d460270bc3ba4"
    end
  end

  def install
    bin.install "config-lint"
  end
end
