# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigLint < Formula
  desc ""
  homepage ""
  version "0.0.43-beta"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stelligent/config-lint/releases/download/v0.0.43-beta/config-lint_0.0.43-beta_Darwin_x86_64.tar.gz"
    sha256 "8e9bd7e0183657dafb6c871e40e2132e9fafc6294a60c42565fa0d2f0ebaac2b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/stelligent/config-lint/releases/download/v0.0.43-beta/config-lint_0.0.43-beta_Linux_x86_64.tar.gz"
      sha256 "87de3abae125058bb0e4c8c7a2c0b8508d4b93a6cc23a60e4192b5e22c40609d"
    end
  end

  def install
    bin.install "config-lint"
  end
end
