# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigLint < Formula
  desc ""
  homepage ""
  version "0.0.40-beta"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stelligent/config-lint/releases/download/v0.0.40-beta/config-lint_0.0.40-beta_Darwin_x86_64.tar.gz"
    sha256 "d5be9524495cfca299de2b9cb66542226a827f79ac074bf31bd00834b4ef8e59"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/stelligent/config-lint/releases/download/v0.0.40-beta/config-lint_0.0.40-beta_Linux_x86_64.tar.gz"
      sha256 "a87ba9d2f6f2f9e77c45eb9725c25800ec32f077d4066fad6519d021350bfdc7"
    end
  end

  def install
    bin.install "config-lint"
  end
end
