# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigLint < Formula
  desc ""
  homepage ""
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stelligent/config-lint/releases/download/v1.0.0/config-lint_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "0b4a4e30611f9006cd1402a65dbf909020425153c940ea76c7308dd6e38fcca8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/stelligent/config-lint/releases/download/v1.0.0/config-lint_1.0.0_Linux_x86_64.tar.gz"
      sha256 "d5db2e9f356441afb2f2fc1b016099db3ca1474c343164f47115e7e064d9d2c5"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stelligent/config-lint/releases/download/v1.0.0/config-lint_1.0.0_Linux_arm64.tar.gz"
        sha256 "b5e69f618a92823ca47ecf477ad9f421d138df385cba14a575b6095bb206b882"
      else
        url "https://github.com/stelligent/config-lint/releases/download/v1.0.0/config-lint_1.0.0_Linux_armv6.tar.gz"
        sha256 "af6d26e759f4500be36c346c5c9ee04b4c5230750cdd42722196688283b14db8"
      end
    end
  end

  def install
    bin.install "config-lint"
  end
end
